version: '3.7'

services:
  spring:
    container_name: group-deal
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/test?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:11
    container_name: mariadb
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
        reservations:
          cpus: '1.0'
          memory: 1024M
    restart: always
    ports:
      - "3308:3306"
    environment:
      MARIADB_DATABASE: 'test'
      MARIADB_ROOT_PASSWORD: '1234'
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/mariadb/data:/var/lib/mysql
      - ./db/mariadb/init:/docker-entrypoint-initdb.d

  mariadb-exporter:
    container_name: mariadb-exporter
    image: prom/mysqld-exporter
    command:
      - "--mysqld.username=root:1234"
      - "--mysqld.address=mariadb:3306"
    ports:
      - "9104:9104"
    depends_on:
      - mariadb
