server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mariadb://localhost:3306/test?serverTimezone=Asia/Seoul
    username: root
    password: ${PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

#  datasource:
#    url: jdbc:mysql://localhost:3306/groupdeal?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: ${PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

logging:
  level:
    com.app.groupdeal: debug

---
###### ?? ?? ######
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.type: trace

---
###### ?? ?? ######
spring:
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.hibernate.type: trace

---
###### ?? ?? ######
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url:
    username:
    password:
    driver-class-name:

  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    com.app.groupdeal: info